# Generated by Django 4.2.19 on 2026-02-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Cтудент: '), ('teacher', 'Преподаватель: '), ('admin', 'Администратор: ')], default='student', max_length=15),
        ),
    ]
